CATALOG = [
    {
        "id": "coast-linen-shirt",
        "audience": "women",
        "brand": "Suitability Studio",
        "name": "Coast linen shirt",
        "category": "shirt",
        "price": 88,
        "color": "Salt white",
        "image": "/garments/coast-linen-shirt.svg",
        "overlay_color": "#e8dfce",
        "material": "European linen",
        "style_tags": ["minimal", "relaxed", "coastal"],
        "formality": ["smart casual", "casual"],
        "weather_tags": ["warm", "mild"],
        "activity_tags": ["dinner", "travel", "daytime"],
        "env_props": {
            "waterproof": 12, "windproof": 18, "insulation": 22,
            "breathability": 92, "uv_protection": 48,
            "temperature_min": 62, "temperature_max": 95,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 41, "waist": 40, "shoulders": 17.5, "sleeves": 23}},
            {"label": "M", "measurements": {"chest": 43, "waist": 42, "shoulders": 18, "sleeves": 24}},
            {"label": "L", "measurements": {"chest": 45, "waist": 44, "shoulders": 18.5, "sleeves": 25}},
        ],
    },
    {
        "id": "terrace-knit-polo",
        "audience": "men",
        "brand": "Northline",
        "name": "Terrace knit polo",
        "category": "shirt",
        "price": 112,
        "color": "Olive",
        "image": "/garments/terrace-knit-polo.svg",
        "overlay_color": "#7d8062",
        "material": "Organic cotton knit",
        "style_tags": ["modern", "minimal", "polished"],
        "formality": ["smart casual", "casual"],
        "weather_tags": ["warm", "mild"],
        "activity_tags": ["dinner", "daytime", "travel"],
        "env_props": {
            "waterproof": 8, "windproof": 22, "insulation": 35,
            "breathability": 78, "uv_protection": 40,
            "temperature_min": 55, "temperature_max": 88,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 40, "waist": 38, "shoulders": 17, "sleeves": 24}},
            {"label": "M", "measurements": {"chest": 42, "waist": 40, "shoulders": 17.5, "sleeves": 25}},
            {"label": "L", "measurements": {"chest": 44, "waist": 42, "shoulders": 18, "sleeves": 26}},
        ],
    },
    {
        "id": "after-hours-blazer",
        "audience": "unisex",
        "brand": "Atelier Nine",
        "name": "After-hours blazer",
        "category": "jacket",
        "price": 178,
        "color": "Ink",
        "image": "/garments/after-hours-blazer.svg",
        "overlay_color": "#30323a",
        "material": "Lightweight twill",
        "style_tags": ["tailored", "modern", "polished"],
        "formality": ["formal", "smart casual"],
        "weather_tags": ["mild", "cold"],
        "activity_tags": ["dinner", "evening", "work"],
        "env_props": {
            "waterproof": 28, "windproof": 55, "insulation": 48,
            "breathability": 62, "uv_protection": 35,
            "temperature_min": 48, "temperature_max": 78,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 41, "waist": 39, "shoulders": 17.5, "sleeves": 24}},
            {"label": "M", "measurements": {"chest": 43, "waist": 41, "shoulders": 18, "sleeves": 25}},
            {"label": "L", "measurements": {"chest": 45, "waist": 43, "shoulders": 18.5, "sleeves": 26}},
        ],
    },
    {
        "id": "weekend-overshirt",
        "audience": "unisex",
        "brand": "Common Ground",
        "name": "Weekend overshirt",
        "category": "shirt",
        "price": 96,
        "color": "Clay",
        "image": "/garments/weekend-overshirt.svg",
        "overlay_color": "#a76248",
        "material": "Brushed cotton",
        "style_tags": ["relaxed", "utility", "minimal"],
        "formality": ["casual"],
        "weather_tags": ["mild", "cold"],
        "activity_tags": ["daytime", "travel", "outdoors"],
        "env_props": {
            "waterproof": 18, "windproof": 42, "insulation": 52,
            "breathability": 70, "uv_protection": 38,
            "temperature_min": 45, "temperature_max": 75,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 43, "waist": 42, "shoulders": 18, "sleeves": 24.5}},
            {"label": "M", "measurements": {"chest": 45, "waist": 44, "shoulders": 18.5, "sleeves": 25.5}},
            {"label": "L", "measurements": {"chest": 47, "waist": 46, "shoulders": 19, "sleeves": 26.5}},
        ],
    },
    {
        "id": "ridge-shell-jacket",
        "audience": "unisex",
        "brand": "Trailform",
        "name": "Ridge shell jacket",
        "category": "jacket",
        "price": 148,
        "color": "Slate",
        "image": "/garments/ridge-shell-jacket.svg",
        "overlay_color": "#4a5560",
        "material": "Recycled nylon shell",
        "style_tags": ["utility", "modern", "relaxed"],
        "formality": ["casual"],
        "weather_tags": ["cold", "mild", "rain"],
        "activity_tags": ["outdoors", "daytime", "travel"],
        "env_props": {
            "waterproof": 88, "windproof": 90, "insulation": 40,
            "breathability": 74, "uv_protection": 55,
            "temperature_min": 35, "temperature_max": 70,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 42, "waist": 40, "shoulders": 18, "sleeves": 24}},
            {"label": "M", "measurements": {"chest": 44, "waist": 42, "shoulders": 18.5, "sleeves": 25}},
            {"label": "L", "measurements": {"chest": 46, "waist": 44, "shoulders": 19, "sleeves": 26}},
        ],
    },
    {
        "id": "midnight-silk-blouse",
        "audience": "women",
        "brand": "Atelier Nine",
        "name": "Midnight silk blouse",
        "category": "shirt",
        "price": 134,
        "color": "Midnight",
        "image": "/garments/midnight-silk-blouse.svg",
        "overlay_color": "#1e2430",
        "material": "Silk crepe",
        "style_tags": ["polished", "tailored", "minimal"],
        "formality": ["formal", "smart casual"],
        "weather_tags": ["warm", "mild"],
        "activity_tags": ["dinner", "evening", "work"],
        "env_props": {
            "waterproof": 5, "windproof": 10, "insulation": 18,
            "breathability": 85, "uv_protection": 20,
            "temperature_min": 60, "temperature_max": 90,
        },
        "sizes": [
            {"label": "S", "measurements": {"chest": 38, "waist": 36, "shoulders": 15.5, "sleeves": 23}},
            {"label": "M", "measurements": {"chest": 40, "waist": 38, "shoulders": 16, "sleeves": 24}},
            {"label": "L", "measurements": {"chest": 42, "waist": 40, "shoulders": 16.5, "sleeves": 25}},
        ],
    },
]

ENVIRONMENTS = {
    "coastal-evening": {
        "id": "coastal-evening",
        "label": "Mediterranean dinner",
        "image": "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 78,
        "conditions": ["warm", "breeze", "evening"],
        "needs": {"breathability": 70, "insulation": 20, "waterproof": 10, "windproof": 25},
    },
    "mountain-trail": {
        "id": "mountain-trail",
        "label": "Mountain trail",
        "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 48,
        "conditions": ["cool", "wind", "outdoors"],
        "needs": {"breathability": 55, "insulation": 55, "waterproof": 50, "windproof": 70},
    },
    "city-evening": {
        "id": "city-evening",
        "label": "City evening",
        "image": "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 58,
        "conditions": ["mild", "night", "urban"],
        "needs": {"breathability": 45, "insulation": 40, "waterproof": 20, "windproof": 40},
    },
    "rooftop-night": {
        "id": "rooftop-night",
        "label": "Rooftop bar",
        "image": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 68,
        "conditions": ["mild", "night", "breeze"],
        "needs": {"breathability": 50, "insulation": 30, "waterproof": 15, "windproof": 45},
    },
    "coast-daylight": {
        "id": "coast-daylight",
        "label": "Beach day",
        "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 84,
        "conditions": ["hot", "sun", "daytime"],
        "needs": {"breathability": 85, "insulation": 10, "waterproof": 5, "windproof": 15, "uv_protection": 60},
    },
    "office-day": {
        "id": "office-day",
        "label": "Office day",
        "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 72,
        "conditions": ["indoor", "mild", "work"],
        "needs": {"breathability": 55, "insulation": 25, "waterproof": 5, "windproof": 10},
    },
    "pool-party": {
        "id": "pool-party",
        "label": "Pool party",
        "image": "https://images.unsplash.com/photo-1575429198097-0414ec70c7b2?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 86,
        "conditions": ["hot", "sun", "casual"],
        "needs": {"breathability": 90, "insulation": 5, "waterproof": 20, "windproof": 10, "uv_protection": 70},
    },
    "winter-city": {
        "id": "winter-city",
        "label": "Winter street",
        "image": "https://images.unsplash.com/photo-1483664852095-d6cc467e59ea?auto=format&fit=crop&w=1600&q=88",
        "temp_f": 28,
        "conditions": ["cold", "wind", "urban"],
        "needs": {"breathability": 35, "insulation": 85, "waterproof": 40, "windproof": 75},
    },
}
